---
id: files
title: Config Files
sidebar_title: Config Files
---
# Admin Panel Settings

A lot of settings can be located in the phpVMS Admin panel, under settings.

---

## Configuration Files

Laravel has a lot of basic configuration in PHP files in the `/config` directory. In order to not overwrite these on an update, there is a way to override these in a `env.php` file in the root of your phpVMS install that is generated by the installer. This contains information  such as the database, mail, and select configs from the `/config` directory. This file is used as an override (in the previous version of phpVMS, the `local.config.php` file is the same concept).

:::caution
Don't change the files in the `/config` directory; instead, edit the `env.php` file instead. These won't be overwritten on an update.
:::

See [Laravel configuration files](https://laravel.com/docs/8.x/configuration#accessing-configuration-values) for additional documentation.

---

### Recaptcha

Recaptcha can be enabled, get the keys [here](https://www.google.com/recaptcha/admin). Then add/change the following to your `env.php` file. The section is there by default, just without the `sitekey` and `secret`.

```php title="env.php"
CAPTCHA_ENABLED=true
CAPTCHA_SITEKEY='YOUR SITE KEY'
CAPTCHA_SECRET='YOUR SITE SECRET'
CAPTCHA_DATATHEME='light'
```
